service: serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

function:
  serverlessFnHello:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: GET
  serverlessFnBye:
    handler: bye.handler
    events:
      - httpApi:
          path: /hello
          method: GET
